# NOTE: This is special config file just for docs_snippets. It's needed because we use a different
# line length in docs_snippets to ensure readability of code blocks in the browser. Unless otherwise
# noted, it should simply copy (except `line-length`) all of the black options from the root
# pyproject.toml (consult that file for explanations of options). This is necessary because
# unfortunately there is no inheritance functionality for black config.

[tool.black]
line-length = 88
preview = true
required-version = "22.10.0"
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
